/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package commerce;
import commerce.dao.CommerceDao;
import commerce.util.Prompt;
import commerce.menu.MenuGroup;
import commerce.handler.commerce.CommerceAddHandler;
import commerce.handler.commerce.CommerceDeleteHandler;
import commerce.handler.commerce.CommerceListHandler;
import commerce.handler.commerce.CommerceModifyHandler;
import commerce.handler.commerce.CommerceViewHandler;
import java.sql.Connection;
import java.sql.DriverManager;

    public class App {

        Prompt prompt = new Prompt(System.in);

        CommerceDao commerceDao;

        MenuGroup mainMenu;

        App() {
            prepareDatabase();
            prepareMenu();
        }

        public static void main(String[] args) {
            System.out.println("[상품관리 시스템]");
            new App().run();
        }

        void prepareDatabase() {

            try {
                Connection con = DriverManager.getConnection(
                    //"jdbc:mysql://localhost/studydb", "study", "Bitcamp!@#123"
                    "jdbc:mysql://db-ld28h-kr.vpc-pub-cdb.ntruss.com/studydb", "study", "Bitcamp!@#123");

                commerceDao = new commerce.dao.mysql.CommerceDaoImpl(con);


            } catch (Exception e) {
                System.out.println("통신오류!");
                e.printStackTrace();
            }
        }


        void prepareMenu() {
            mainMenu = MenuGroup.getInstance("메인");

            MenuGroup commerceMenu = mainMenu.addGroup("상품");
            commerceMenu.addItem("등록", new commerce.handler.commerce.CommerceAddHandler(commerceDao, prompt));
            commerceMenu.addItem("조회", new commerce.handler.commerce.CommerceViewHandler(commerceDao, prompt));
            commerceMenu.addItem("변경", new commerce.handler.commerce.CommerceModifyHandler(commerceDao, prompt));
            commerceMenu.addItem("삭제", new commerce.handler.commerce.CommerceDeleteHandler(commerceDao, prompt) );
            commerceMenu.addItem("목록", new commerce.handler.commerce.CommerceListHandler(commerceDao, prompt));


        }
        void run() {
            while (true) {
                try {
                    mainMenu.execute(prompt);
                    prompt.close();
                    break;
                } catch (Exception e) {
                    System.out.println("예외 발생!");
                }
            }
        }
    }


