/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.myapp;

public class App {

  public static void main(String[] args) {

    MainMenu.excute();
    Prompt.close();
  }


}


